### ISSUE TITLE
Pick a License, Any License

### ISSUE THREAD

**Issue by jhabdas** [sudar/wp-plugin-in-github#22]
https://blog.codinghorror.com/pick-a-license-any-license/

**Comment by sudar** [comment]
@jhabdas 

This project does have a license - https://github.com/sudar/wp-plugin-in-github#license

Were you looking for something more 'formal'?

**Comment by jhabdas** [comment]
I missed that the first time through. But its really up to you. Perhaps a valid SPDX license would be more appropriate to facilitate reuse. Feel free to reopen this issue. Cheers.

**Comment by sudar** [comment]
@jhabdas 

Beerware is in fact a valid SPDX license - https://spdx.org/licenses/Beerware.html More details about Beerware - https://en.wikipedia.org/wiki/Beerware

I am curious to know whether the fact that this project is in Beerware is limiting you to reuse it in any way. If yes, then let me know and I can release it under a dual license of Beerware and what ever license you require.
