### ISSUE TITLE
If a file is removed in git, remove it from svn as well

### ISSUE THREAD

**Issue by sudar** [sudar/wp-plugin-in-github#8]

**Comment by blockonomics** [comment]
Just discovered this today. Need this as well :dango:

**Comment by sudar** [comment]
Yeah, it's been in my todo list for long time. Will try to get it implemented when I get some free time.

**Comment by blockonomics** [comment]
Thanks. I will also see if I can get time to do this

**Comment by sudar** [comment]
Perfect. Would love to see an Pull request :)

**Comment by shivaenigma** [comment]
Did some research. Does this work https://stackoverflow.com/a/25492747/5043010

**Comment by sudar** [comment]
Yeah the above works. But we just need to wrap it in a conditional so that if there are no files to delete it doesn't generate an error.
